sudo: required
os: linux
dist: focal
compiler: gcc
language: c


addons:
  apt:
    packages:
    - libpcap-dev

matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
          - libpcap-dev
          - autogen
    - os: linux
      dist: trusty
      compiler: gcc
      env: CI_BUILD_PREFIX=scan-build-9.3
      addons:
        apt:
          packages:
          - libpcap-dev
          - autogen

before_script:
- git pull --tags

script:
  - autoreconf -iv > build.log 2>&1 || (cat build.log && exit 1)
  - ${CI_BUILD_PREFIX} ./configure --disable-local-libopts --enable-asan > build.log 2>&1 || (cat build.log && exit 1)
  - ${CI_BUILD_PREFIX} make > build.log 2>&1 || (cat build.log && exit 1)
  - make dist > build.log 2>&1 || (cat build.log && exit 1)
  - sudo make test || (cat test/test.log && exit 1)
